# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(blank=True, default=b'', max_length=500, null=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, default=b'', max_length=1000, null=True)),
                ('abstract', models.CharField(blank=True, default=b'', max_length=10000, null=True)),
                ('reference', models.CharField(blank=True, default=b'', max_length=100000, null=True)),
                ('year', models.CharField(blank=True, default=b'', max_length=10, null=True)),
                ('wom', models.CharField(blank=True, default=b'', max_length=50, null=True)),
            ],
        ),
    ]
